### ISSUE TITLE
Official Aegisub website

### ISSUE THREAD

**Issue by seproDev** [computerfan/Chinese-aegisite#9]
Hey, with Aegisub hopefully soon™ having a functional site again, I wanted to reach out to you. The new Aegisite supports multiple languages, and we decided to integrate your work from here.

You can view the current version [here](https://aegisite.vercel.app/), but hopefully in the not so distant future the site should also be accessible on aegisub.org again. Currently, a compiled version of your current 3.2 docs are served at [/zh-cn/docs/3.2/](https://aegisite.vercel.app/zh-cn/docs/3.2/Main_Page/) as sort of a historical reference. While the markdown files are compiled with the new theme at [/zh-cn/docs/latest/](https://aegisite.vercel.app/zh-cn/docs/latest/main_page/). 

I guess there are a couple of things I wanted to ask you:
 - Is there anything I ported over incorrectly?
 - Do you have any other feedback regarding the new site?
 - What do you want to happen with [aegi.vmoe.info](http://aegi.vmoe.info/)? If you are okay with it maybe the site could redirect to aegisub.org/zh-cn/ once that is live.

**Comment by computerfan** [comment]
Hi, nice to see it will be back online soon. I've been following the progress of moving to Hugo and found some random issues like missing closing bracket on the third line at [/zh-cn/docs/latest/tutorials/](https://aegisite.vercel.app/zh-cn/docs/latest/tutorials/). I think I'll have the other translators check most pages and create a pull request to fix them later.

I hope a list of translation contributors can be added on the credits page. Although the footer has a link to the contributors of this repo, some commits in this repo were submitted on behalf of translators who are unfamiliar with Git.

Also, The new theme doesn't look like it was designed for Chinese. I may need to make some tweaks.

I plan to sync aegi.vmoe.info to the latest Hugo version and maintain as a mirror site to ensure better availability for Chinese users and our fansub. I will block search engines if there are any SEO issues.

Thanks for your work and happy new year!

**Comment by seproDev** [comment]
Alright sounds good! In my most recent PR I moved a couple more hardcoded strings in to the i18n files which allows for easier translation. If there are any tweaks you would like me to look in to, I'd be happy to do that. Otherwise, feel free to make PRs with the changes you would like to see.
